name: family_report_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  usage_stats: ^0.1.0
  cupertino_icons: ^1.0.2
  app_usage: ^1.2.0
  provider: ^5.0.0
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_messaging: ^9.1.1
  firebase_storage: ^8.0.3
  cloud_firestore: ^1.0.1
  firebase_dynamic_links: ^0.8.0
  shared_preferences: ^2.0.5
  uuid: ^3.0.4
  image_picker: ^0.7.4
  flutter_spinkit: "^4.1.2"
  flutter_local_notifications: ^5.0.0+1
  rxdart: ^0.23.1
  timezone: ^0.7.0
  flutter_native_timezone: ^1.0.10
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
